services:
  db:
    image: postgres:latest
    restart: always
    env_file: ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10

  journal:
    image: ghcr.io/reuben-good/neuejournal:latest
    env_file: ".env"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
