# Generated by Django 6.0.4 on 2026-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "happiness",
                    models.DecimalField(
                        choices=[
                            ("very-sad", -1.0),
                            ("sad", -0.5),
                            ("neutral", 0.0),
                            ("happy", 0.5),
                            ("very-happy", 1.0),
                        ],
                        decimal_places=1,
                        max_digits=2,
                    ),
                ),
            ],
        ),
    ]
