# Generated by Django 6.0.4 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='happiness',
            field=models.DecimalField(choices=[('very-sad', -1.0), ('sad', -0.5), ('neutral', 0.0), ('happy', 0.5), ('very-happy', 1.0)], decimal_places=1, max_digits=2),
        ),
    ]
