# Generated by Django 6.0.4 on 2026-04-22 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_mood_happiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mood',
            unique_together={('owner', 'entry')},
        ),
    ]
