# Generated by Django 6.0.4 on 2026-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_mood_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('milestone', 'Milestone'), ('lesson', 'Lesson'), ('event', 'Event')], default='milestone', max_length=20),
        ),
    ]
