# Generated by Django 6.0.4 on 2026-05-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_entry_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
    ]
