# Generated by Django 6.0.4 on 2026-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_journalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsettings',
            name='colour',
            field=models.CharField(default='8ecae6', max_length=6),
        ),
    ]
