# Generated by Django 6.0.4 on 2026-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journalsettings_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsettings',
            name='colour',
            field=models.CharField(default='6f4518', max_length=6),
        ),
    ]
