# Generated by Django 6.0.4 on 2026-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_journalsettings_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='email_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
