# Generated by Django 6.0.4 on 2026-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_photo_email_token_photo_email_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsettings',
            name='belongs_to',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
