# Generated by Django 6.0.4 on 2026-05-18 18:06

import apps.helpers.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_journalsettings_belongs_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=apps.helpers.storages.sticker_storage, upload_to='')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.stickerpack')),
            ],
        ),
    ]
