# Generated by Django 6.0.4 on 2026-05-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_ownedpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='journal.stickerpack'),
        ),
    ]
