# Generated by Django 6.0.4 on 2026-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_stickerposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerposition',
            name='page',
            field=models.CharField(max_length=200),
        ),
    ]
