# Generated by Django 6.0.4 on 2026-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_alter_stickerposition_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerposition',
            name='x',
            field=models.DecimalField(decimal_places=2, default=64, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stickerposition',
            name='y',
            field=models.DecimalField(decimal_places=2, default=64, max_digits=5),
        ),
    ]
