# Generated by Django 6.0.4 on 2026-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_alter_stickerposition_x_alter_stickerposition_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerposition',
            name='height',
            field=models.DecimalField(decimal_places=2, default=64, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stickerposition',
            name='width',
            field=models.DecimalField(decimal_places=2, default=64, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stickerposition',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stickerposition',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
