# Generated by Django 6.0.4 on 2026-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_alter_stickerposition_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerposition',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stickerposition',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
